import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.css";
import Header from ".././components/header/header";
import MainMenu from "@/components/mainMenu/mainMenu";
import MenuContextProvider from "@/containers/menuContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MenuContextProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className} suppressHydrationWarning={true}>
          <div className={styles.container}>
            <Header />
            <div className={styles.containerLayout}>
              {/* menu */}
              <div className={styles.containerMenu}>
                <MainMenu />
              </div>
              {/* children */}
              <div className={styles.containerChildren}>{children}</div>
            </div>
          </div>
        </body>
      </html>
    </MenuContextProvider>
  );
}
